{% set name = "json-fortran" %}
{% set version = "8.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jacobwilliams/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 71924c3bdd04ea37ddceb13c1b9e1e4a8f944b1ffab6285e5c5b1283cced2da8

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex
    - cmake ${CMAKE_ARGS} -B_build -GNinja -DUSE_GNU_INSTALL_CONVENTION=true -DSKIP_DOC_GEN=true
    - cmake --build _build
    - cmake --build _build --target check  # [build_platform == target_platform]
    - cmake --install _build
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - cmake
    - ninja

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}  # [build_platform == target_platform]
    - test -f $PREFIX/lib/libjsonfortran$SHLIB_EXT

about:
  home: https://github.com/jacobwilliams/json-fortran
  license: BSD-3-Clause AND MIT
  license_file: LICENSE
  summary: Modern Fortran JSON API
  doc_url: https://jacobwilliams.github.io/json-fortran/

extra:
  recipe-maintainers:
    - awvwgk
    - jacobwilliams
