conda_forge_output_validation: true
provider:
  linux_ppc64le: default
  linux_aarch64: default
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
